version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/docker-database-init.sql:/docker-entrypoint-initdb.d/docker-database-init.sql   

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "yourAddress@email.com"
      PGADMIN_DEFAULT_PASSWORD: "111111"
    ports:
      - "54321:80"
    depends_on:
      - postgres